AndroidMarket/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AndroidMarket.Models;
using System.IO;
using AndroidMarket.Helpers;
using AndroidMarket.Models.Entities;
using AndroidMarket.Models.ModelViews;

namespace AndroidMarket.Controllers
{
    public class ApplicationsController : Controller
    {
        //private AndroidMarketContext db = new AndroidMarketContext();
        private DbRepository _repository = new DbRepository();

        //
        // GET: /Default1/

        [Authorize]
        public ActionResult Index(String id)
        {
            if(String.IsNullOrEmpty(id))
                return View(_repository.Applications.ToList());
            else
            {
                return View(_repository.GetApplicationsByGradeName(id));
            }
        }

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id = 0)
        {
            var application = _repository.Applications.Include("Screenshots").Where(a => a.ApplicationId == id).FirstOrDefault();
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        //
        // GET: /Default1/Create
        [Authorize]
        public ActionResult Create()
        {
            var grades = _repository.Grades.ToList();//.GetGrades();
            return View(new CreateApplicationViewModel(null,grades));
        }

        //
        // POST: /Default1/Create

        [HttpPost]
        [Authorize]
        public ActionResult Create(Application application,
            HttpPostedFileBase Apk,            
            HttpPostedFileBase Thumbnail)
        
        {
            if(ModelState.IsValid)
            {
                var apkFile = new AndroidMarket.Models.Entities.File() { DownloadedCounter = 0, FileName = Apk.FileName, FileType = "Apk", Size = Apk.ContentLength, StorageName = Guid.NewGuid().ToString()+".apk" };
                var thumbnailFile = new AndroidMarket.Models.Entities.File() { DownloadedCounter = 0, FileName = Thumbnail.FileName, FileType = "Image", Size = Thumbnail.ContentLength, StorageName = Guid.NewGuid().ToString()+".jpg" };
                application.Apk = apkFile;
                application.Thumbnail = thumbnailFile;
                _repository.AddApplication(application);
                _repository.SaveChanges();                
                FilesHelper.SaveFile(Apk,apkFile.StorageName,FileType.Apk);
                FilesHelper.SaveFile(Thumbnail,thumbnailFile.StorageName, FileType.Image);              
                return RedirectToAction("Index");
            }
            var grades = _repository.Grades.ToList();//.GetGrades();
            return View(new CreateApplicationViewModel(application,grades));
        }
   
        //
        // GET: /Default1/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            
            Application application = _repository.Applications.Where(app=>app.ApplicationId==id).FirstOrDefault();//.Get(id);
            if (application == null)
            {
                return HttpNotFound();
            }
           
            return View(new CreateApplicationViewModel(application,_repository.Grades.ToArray()));//.GetGrades()));
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        [Authorize]
        public ActionResult Edit(Application application)
        {
            if (ModelState.IsValid)
            {
                _repository.UpdateApplication(application);
                _repository.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(new CreateApplicationViewModel(application,_repository.Grades.ToArray()));//.GetGrades()));
        }

        //
        // GET: /Default1/Delete/5
       [Authorize]
        public ActionResult Delete(int id = 0)
        {
            var application = _repository.Applications.Where(a=>a.ApplicationId==id).FirstOrDefault();//.Get(id);// db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        //
        // POST: /Default1/Delete/5

       [HttpPost, ActionName("Delete")]
       [Authorize]
       public ActionResult DeleteConfirmed(int id)
       {
           var app = (from a in _repository.Applications.Include("Apk").Include("Thumbnail").Include("Screenshots")
                      where a.ApplicationId == id
                      select a).FirstOrDefault();
           var screenshots = app.Screenshots.ToList();
           var thumbnail = app.Thumbnail;
           var apk = app.Apk;
           foreach (var screenshot in screenshots)
           {
               _repository.DeleteScreenshot(screenshot);
               FilesHelper.DeleteFile(screenshot.Image.StorageName, FileType.Image);
           }
           _repository.DeleteFile(thumbnail);
           _repository.DeleteFile(apk);
           _repository.RemoveApplication(app);
           _repository.SaveChanges();
           FilesHelper.DeleteFile(apk.StorageName, FileType.Apk);
           FilesHelper.DeleteFile(thumbnail.StorageName, FileType.Image);

           return RedirectToAction("Index");
       }

     

        protected override void Dispose(bool disposing)
        {
            _repository.Dispose();
            base.Dispose(disposing);
        }

        public FileResult Market()
        {
     
            var contentType = "application/octet-stream";
            var apkName="RainbowMarket.apk";
            var filePath =System.Web.HttpContext.Current.Server.MapPath(FilesHelper.ResolvePath(FileType.Apk, apkName));

            return File(filePath, contentType, apkName);
        }
    }
}

AndroidMarket/Controllers/HomeController.cs
using System;
using AndroidMarket.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AndroidMarket.Models.Entities;
using AndroidMarket.Models.ModelViews;

namespace AndroidMarket.Api.Controllers
{
    public class HomeController : Controller,IDisposable
    {
        private DbRepository _repository = new DbRepository();
        [OutputCache(Duration=30)]
        public ActionResult Index(string id)
        {
            var grades = _repository.Grades.ToArray();
            IEnumerable<Application> apps = null;
            if (!string.IsNullOrEmpty(id))
                apps = _repository.GetApplicationsByGradeName(id);
            return View(new GradesApplicationsViewModel(apps,grades));
        }
        new public  void Dispose()
        {
            _repository.Dispose();
            _repository = null;
            base.Dispose();
        }
        public ActionResult About()
        {
            return View();
        }

        

    }
}

AndroidMarket/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2>About</h2>

AndroidMarket/Views/Home/Index.cshtml
@model AndroidMarket.Models.ModelViews.GradesApplicationsViewModel
@using AndroidMarket.Helpers

@{
    ViewBag.Title= "التطبيقات";
}

<div id="body">
    @using (Html.BeginForm(null, null, FormMethod.Get))
    {
        <div class="float-right">
            المرحلة الدراسية
        </div>
        <div class="float-right">
            @Html.DropDownList("id", new SelectList(Model.Grades, "Name", "Name"),"<المرحلة الدراسية>", new { onchange = "submitGrade(this);" })
        </div>            
    }
    <div class="clear-fix"></div>
    <hr />

    <div class="items-container">
        @if (Model.Applications != null)
        {
            foreach (var app in Model.Applications)
            {		 	
            <div class="item">
                <div class="item-wrapper">
                    <div class="item-thumbnail-wrapper">
                        <a class="thumbnail-href" href="@Url.Action("Details", "Applications", new { id = app.ApplicationId })">
                            <img src="@Html.GetThumbnailPath(app.Thumbnail.StorageName)" class="thumbnail-img" />
                        </a>
                    </div>
                    <div class="item-detail">
                        <span class="item-title">@Html.DisplayFor(m => app.Name)</span>
                    </div>
                    <div class="item-description-wrapper">
                        <div class="item-description">
                            <a href="@Url.Action("Details", "Applications", new { id = app.ApplicationId })">
                                <span>تفاصيل</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            }
        }
    </div>

</div>


<script type="text/javascript">

    function submitGrade(item) {
        if($(item).val()!="<المرحلة الدراسية>")
        $(item).closest("form").submit();
    }


    //$(document).ready () ->
    // $("select#menu_id").change(-> $(this).closest("form").submit())
</script>